language: node_js
node_js: "lts/*"
cache: yarn
install: yarn --ignore-engines
script:
  - yarn lint
  - yarn test
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
  skip_cleanup: true
